---
- name: Setup Proxmox VE on Hyper-V
  hosts: hyperv
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure Hyper-V feature is installed
      win_feature:
        name: Microsoft-Hyper-V-All
        state: present

    - name: Download Proxmox VE ISO
      win_get_url:
        url: "{{ proxmox_iso_url }}"
        dest: "{{ iso_download_path }}"

    - name: Create Hyper-V VM for Proxmox
      win_shell: |
        New-VM -Name {{ vm_name }} -MemoryStartupBytes {{ vm_memory }} -NewVHDPath "{{ vm_disk_path }}" -NewVHDSizeBytes {{ vm_disk_size }} -Generation 2
        Set-VM -Name {{ vm_name }} -MemoryStartupBytes {{ vm_memory }}
        Add-VMHardDiskDrive -VMName {{ vm_name }} -Path "{{ vm_disk_path }}"
        Add-VMDvdDrive -VMName {{ vm_name }} -Path "{{ iso_download_path }}"
        Connect-VMNetworkAdapter -VMName {{ vm_name }} -SwitchName "{{ switch_name }}"
        Start-VM -Name {{ vm_name }}

    - name: Wait for Proxmox VE installation to complete
      pause:
        minutes: 20

    - name: Configure Proxmox VE network settings
      win_shell: |
        $vm = Get-VM -Name {{ vm_name }}
        $vm | Get-VMNetworkAdapter | Set-VMNetworkAdapter -MacAddressSpoofing On
        $vm | Set-VMNetworkAdapterVlan -Access -VlanId 100
